# Generated by Django 6.0.1 on 2026-07-02 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('number_of_shares', models.PositiveIntegerField()),
                ('percentage_ownership', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Shareholder',
                'verbose_name_plural': 'Shareholders',
                'db_table': 'shareholders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyShareholding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('numbers_of_shares', models.PositiveIntegerField()),
                ('numbers_of_shareholders', models.PositiveIntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shareholdings', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Shareholding',
                'verbose_name_plural': 'Company Shareholdings',
                'db_table': 'company_shareholding',
                'ordering': ['-numbers_of_shares'],
            },
        ),
    ]
