# Generated by Django 6.0.1 on 2026-07-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholding', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyshareholding',
            name='authorized_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Authorized Capital'),
        ),
        migrations.AddField(
            model_name='companyshareholding',
            name='paid_up_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Paid Up Capital'),
        ),
    ]
