# Generated by Django 6.0.1 on 2026-07-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholding', '0003_companyshareholding_authorized_capital_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyshareholding',
            options={'verbose_name': 'Company Shareholding', 'verbose_name_plural': 'Company Shareholdings'},
        ),
        migrations.RemoveField(
            model_name='companyshareholding',
            name='numbers_of_shares',
        ),
        migrations.RemoveField(
            model_name='companyshareholding',
            name='paid_up_capital',
        ),
        migrations.AddField(
            model_name='companyshareholding',
            name='issued_share_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Issued Share Capital'),
        ),
    ]
