# Generated by Django 6.0.1 on 2026-07-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholding', '0004_alter_companyshareholding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholder',
            name='is_pep',
            field=models.BooleanField(default=False),
        ),
    ]
