# Generated by Django 6.0.1 on 2026-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholding', '0005_shareholder_is_pep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyshareholding',
            name='numbers_of_shareholders',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
