# Generated by Django 6.0.1 on 2026-08-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholding', '0006_alter_companyshareholding_numbers_of_shareholders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='percentage_ownership',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
