# Generated by Django 6.0.1 on 2026-08-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareholding', '0007_alter_shareholder_percentage_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='number_of_shares',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
