# Generated by Django 6.0.1 on 2026-07-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('registered_name', models.CharField(help_text='', max_length=200, unique=True)),
                ('trading_name', models.CharField(blank=True, help_text='The name the company trades under, if different from registration name.', max_length=255, null=True, unique=True)),
                ('refer_type', models.CharField(choices=[('biu', 'BIU'), ('fp3', 'FP3'), ('rentsafe', 'Rentsafe')], default='biu', help_text='Where was company data retrieved from, default is BIU.', max_length=10)),
                ('location', models.CharField(blank=True, choices=[('city_centre', 'City Centre'), ('industrial', 'Industrial'), ('suburban', 'Suburban'), ('rural', 'Rural')], max_length=20, null=True)),
                ('site_ownership', models.CharField(blank=True, choices=[('owners', 'Owners'), ('rented', 'Rented')], max_length=25, null=True)),
                ('address_registered', models.TextField()),
                ('address_operations', models.TextField(blank=True)),
                ('prev_addresses', models.JSONField(blank=True, null=True, verbose_name="\n        prev[]: address : '....',\n            field :  registered | operation\n            created_at: timestamp\n    ")),
                ('email', models.EmailField(blank=True, help_text='General email address for the company.', max_length=255, null=True)),
                ('telephone_number', models.CharField(blank=True, help_text='General telephone number for the company.', max_length=20, null=True)),
                ('mobile_number', models.CharField(blank=True, help_text='General phone number for the company.', max_length=20, null=True)),
                ('website', models.URLField(blank=True, help_text='Website link for the branch.', max_length=255, null=True)),
                ('is_address_registered_verified', models.BooleanField(default=True)),
                ('is_company_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('target_markets', models.TextField(blank=True)),
                ('operations_territories', models.TextField(blank=True)),
                ('property_ownership', models.TextField(blank=True)),
                ('operational_areas', models.TextField(blank=True)),
                ('import_export', models.TextField(blank=True, help_text='Import / Export details')),
                ('purchases_payment_terms', models.CharField(blank=True, choices=[('cash_only', 'Cash Only'), ('cash_and_credit', 'Cash & Credit'), ('credit_only', 'Credit Only')], max_length=50, null=True)),
                ('sales_payment_terms', models.CharField(blank=True, choices=[('cash_only', 'Cash Only'), ('cash_and_credit', 'Cash & Credit'), ('credit_only', 'Credit Only')], max_length=50, null=True)),
                ('purchase_supplier_scope', models.CharField(blank=True, choices=[('local', 'Local Suppliers'), ('international', 'International Suppliers'), ('local_&_international', 'Local & International Suppliers')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'company_operations',
                'verbose_name_plural': 'Company Operations',
            },
        ),
        migrations.CreateModel(
            name='CompanyOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('trading_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], max_length=20, null=True)),
                ('date_of_registration', models.DateField(blank=True, null=True)),
                ('legal_form', models.CharField(blank=True, choices=[('llc', 'LLC'), ('plc', 'PLC'), ('sole_trader', 'Sole Trader'), ('partnership', 'Partnership')], max_length=20, null=True)),
                ('condition', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True)),
                ('trend', models.CharField(blank=True, choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20, null=True)),
                ('number_of_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('last_financial_result', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_asset_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('authorized_share_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('issued_share_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'verbose_name': 'Company Overview',
                'verbose_name_plural': 'Company Overviews',
                'db_table': 'company_overview',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('holding_company', models.TextField(blank=True, help_text='Holding company name', null=True)),
                ('subsidiaries', models.TextField(blank=True, help_text='List of subsidiaries', null=True)),
                ('associated_companies', models.TextField(blank=True, help_text='List of associated companies', null=True)),
                ('divisions', models.TextField(blank=True, help_text='List of divisions', null=True)),
                ('branches', models.TextField(blank=True, help_text='List of branches', null=True)),
            ],
            options={
                'verbose_name': 'Company Structure',
                'verbose_name_plural': 'Company Structures',
            },
        ),
    ]
