# Generated by Django 6.0.1 on 2026-07-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, null=True, verbose_name='Company Registration Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_name',
            field=models.CharField(help_text='', max_length=200, unique=True),
        ),
    ]
