# Generated by Django 6.0.1 on 2026-07-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registered_name',
            field=models.CharField(help_text='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, help_text='Website link for the branch.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companyoverview',
            name='legal_form',
            field=models.CharField(blank=True, choices=[('pvt_ltd', 'Private Limited'), ('plc', 'PLC'), ('pbc', 'Public Benefit Company'), ('partnership', 'Partnership'), ('trust', 'Trust'), ('joint_venture', 'Joint Venture'), ('cooperative', 'Cooperative'), ('sole_trader', 'Sole Trader')], max_length=20, null=True),
        ),
    ]
