# Generated by Django 6.0.1 on 2026-07-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_registered_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyoverview',
            name='date_of_registration',
        ),
        migrations.AddField(
            model_name='company',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_name',
            field=models.CharField(help_text='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='companyoverview',
            name='trading_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('administration', 'Administration'), ('insolvent', 'Insolvent')], max_length=20, null=True),
        ),
    ]
