# Generated by Django 6.0.1 on 2026-07-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_companyoverview_date_of_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registered_name',
            field=models.CharField(help_text='', max_length=200, unique=True),
        ),
    ]
