# Generated by Django 6.0.1 on 2026-07-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_company_registered_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyoverview',
            name='authorized_share_capital',
        ),
        migrations.RemoveField(
            model_name='companyoverview',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='companyoverview',
            name='issued_share_capital',
        ),
        migrations.RemoveField(
            model_name='companyoverview',
            name='last_financial_result',
        ),
        migrations.RemoveField(
            model_name='companyoverview',
            name='net_asset_value',
        ),
        migrations.RemoveField(
            model_name='companyoverview',
            name='trend',
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_name',
            field=models.CharField(help_text='', max_length=200, unique=True),
        ),
    ]
