# Generated by Django 6.0.1 on 2026-07-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_alter_company_registered_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='General phone number for the company.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_name',
            field=models.CharField(help_text='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone_number',
            field=models.CharField(blank=True, help_text='General telephone number for the company.', max_length=200, null=True),
        ),
    ]
