# Generated by Django 6.0.1 on 2026-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_alter_company_registered_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_of_incorporation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='re_registration_number',
            field=models.CharField(blank=True, null=True, verbose_name='Company Re-Registration Number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registered_name',
            field=models.CharField(help_text='', max_length=200, unique=True),
        ),
    ]
