# Generated by Django 6.0.1 on 2026-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0030_alter_company_registered_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registered_name',
            field=models.CharField(help_text='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='companyoperations',
            name='purchase_supplier_scope',
            field=models.CharField(blank=True, choices=[('local', 'Local Suppliers'), ('international', 'International Suppliers'), ('local_and_international', 'Local And International Suppliers')], max_length=50, null=True),
        ),
    ]
