# Generated by Django 6.0.1 on 2026-08-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_alter_company_registered_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registered_name',
            field=models.CharField(help_text='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='companyoperations',
            name='import_export',
            field=models.TextField(blank=True, help_text='Import / Export details', null=True),
        ),
        migrations.AlterField(
            model_name='companyoperations',
            name='industry',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='companyoperations',
            name='operational_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyoperations',
            name='operations_territories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyoperations',
            name='property_ownership',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyoperations',
            name='target_markets',
            field=models.TextField(blank=True, null=True),
        ),
    ]
