# Generated by Django 6.0.1 on 2026-08-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0036_alter_company_email_alter_company_registered_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registered_name',
            field=models.CharField(help_text='', max_length=200, unique=True),
        ),
    ]
