# Generated by Django 6.0.1 on 2026-08-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0047_alter_company_registered_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='trading_name',
            field=models.CharField(blank=True, help_text='The name the company trades under, if different from registration name.', max_length=255, null=True),
        ),
    ]
