# Generated by Django 6.0.1 on 2026-07-02 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(help_text='Director full name', max_length=50)),
                ('position', models.CharField(choices=[('director', 'Director'), ('secretary', 'Secretary'), ('other', 'Other')], default='director', help_text='Director position in the company', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('national_id', models.CharField(max_length=15, verbose_name='National ID | Passport Number')),
                ('insolvencies_judgements', models.TextField(blank=True, null=True, verbose_name='Insolvencies, Judgements, Defaults')),
                ('dob', models.DateTimeField(blank=True, help_text='Director Date of birth', null=True)),
                ('address_latest', models.TextField(help_text='Director Primary Address')),
                ('address_prev', models.TextField(blank=True, help_text='Director Prev Address', null=True)),
                ('email', models.EmailField(blank=True, help_text='Director Email', max_length=50, null=True)),
                ('mobile_phone_number', models.CharField(blank=True, help_text='Director Mobile Phone Number', max_length=50, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Director',
                'verbose_name_plural': 'Company Directors',
                'db_table': 'company_directors',
                'ordering': ['-created_at'],
            },
        ),
    ]
