# Generated by Django 6.0.1 on 2026-07-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydirector',
            name='is_pep',
            field=models.BooleanField(default=False),
        ),
    ]
