# Generated by Django 6.0.1 on 2026-07-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0003_companydirector_is_pep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydirector',
            name='dob',
            field=models.DateField(blank=True, help_text='Director Date of birth', null=True),
        ),
    ]
