# Generated by Django 6.0.1 on 2026-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0004_alter_companydirector_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydirector',
            name='position',
            field=models.CharField(choices=[('director', 'Director'), ('secretary', 'Secretary'), ('chairman', 'Chairman'), ('other', 'Other')], default='director', help_text='Director position in the company', max_length=20),
        ),
    ]
