# Generated by Django 6.0.1 on 2026-08-06 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0005_alter_companydirector_position'),
        ('individuals', '0004_individuals_address_prev_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydirector',
            name='address_latest',
        ),
        migrations.RemoveField(
            model_name='companydirector',
            name='address_prev',
        ),
        migrations.RemoveField(
            model_name='companydirector',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='companydirector',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companydirector',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='companydirector',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='companydirector',
            name='insolvencies_judgements',
        ),
        migrations.RemoveField(
            model_name='companydirector',
            name='is_pep',
        ),
        migrations.RemoveField(
            model_name='companydirector',
            name='mobile_phone_number',
        ),
        migrations.RemoveField(
            model_name='companydirector',
            name='national_id',
        ),
        migrations.AddField(
            model_name='companydirector',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directorships', to='individuals.individuals'),
        ),
    ]
