# Generated by Django 6.0.1 on 2026-08-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0006_remove_companydirector_address_latest_and_more'),
        ('individuals', '0005_alter_individuals_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydirector',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directorship', to='individuals.individuals'),
        ),
    ]
