# Generated by Django 6.0.1 on 2026-08-28 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directors', '0007_alter_companydirector_individual'),
        ('individuals', '0008_alter_individuals_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydirector',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directorship', to='individuals.individuals'),
        ),
    ]
