# Generated by Django 6.0.1 on 2026-07-02 08:44

import apps.common.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject_object_id', models.PositiveIntegerField()),
                ('total_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total Assets')),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Net Profit')),
                ('net_worth', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Net Worth')),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total Revenue')),
                ('paid_up_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Paid Up Capital')),
                ('authorized_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Authorized Capital')),
                ('financials_file', models.FileField(blank=True, null=True, upload_to=apps.common.models.Financials.financials_file_path, verbose_name='Financials File')),
                ('financial_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Financial Year')),
            ],
            options={
                'verbose_name': 'Financials',
                'verbose_name_plural': 'Financials',
                'db_table': 'financials',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject_object_id', models.PositiveIntegerField()),
                ('auditors', models.TextField()),
                ('lawyers', models.TextField()),
            ],
            options={
                'verbose_name': 'Professional Partner',
                'verbose_name_plural': 'Professional Partners',
                'db_table': 'professional_partners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject_object_id', models.PositiveIntegerField()),
                ('tin_number', models.CharField(blank=True, help_text='Account tin number', max_length=50, null=True)),
                ('vat_number', models.CharField(blank=True, help_text='Account vat number', max_length=50, null=True)),
                ('nssa_number', models.CharField(blank=True, help_text='Account nssa number', max_length=50, null=True)),
                ('praz_number', models.CharField(blank=True, help_text='Account praz number', max_length=50, null=True)),
                ('is_praz_verified', models.BooleanField(default=False)),
                ('is_nssa_verified', models.BooleanField(default=False)),
                ('is_vat_verified', models.BooleanField(default=False)),
                ('is_tin_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Registration Account',
                'verbose_name_plural': 'Registration Accounts',
                'db_table': 'registration_accounts',
            },
        ),
        migrations.CreateModel(
            name='TradeReferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject_object_id', models.PositiveIntegerField()),
                ('referenced_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_source', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_limit', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_trend', models.CharField(blank=True, choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Trade Reference',
                'verbose_name_plural': 'Trade Reference',
                'db_table': 'trade_references',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankerAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject_object_id', models.PositiveIntegerField()),
                ('bank', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZiG', 'Zimbabwe Gold'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('ZAR', 'South African Rand')], default='USD', max_length=5)),
                ('account_type', models.CharField(choices=[('current', 'Current'), ('savings', 'Savings'), ('loan', 'Loan'), ('fixed_deposit', 'Fixed Deposit')], max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('date_of_acquirement', models.DateField(auto_now=True)),
                ('bank_code', models.CharField(blank=True, max_length=10, null=True)),
                ('narration', models.CharField(choices=[('A', 'Very Good Credit Worthiness (Lowest Risk)'), ('B', 'Good Credit Worthiness (Low Risk)'), ('C', 'Satisfactory Credit Worthiness (Moderate Risk)'), ('D', 'No Credit Worthy'), ('E', 'Rating Suspended')], default='A', max_length=2)),
                ('subject_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subject', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Banker Account',
                'verbose_name_plural': 'Banker Accounts',
                'db_table': 'bank_accounts',
            },
        ),
    ]
