# Generated by Django 6.0.1 on 2026-07-02 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankeraccounts',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financials',
            name='subject_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subject', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='financials',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionalpartners',
            name='subject_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subject', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='professionalpartners',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrationaccounts',
            name='subject_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subject', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='registrationaccounts',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradereferences',
            name='subject_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subject', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='tradereferences',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='financials',
            constraint=models.UniqueConstraint(fields=('subject_content_type', 'subject_object_id'), name='unique_financials_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='professionalpartners',
            constraint=models.UniqueConstraint(fields=('subject_content_type', 'subject_object_id'), name='unique_professional_partners_per_subject'),
        ),
        migrations.AddConstraint(
            model_name='registrationaccounts',
            constraint=models.UniqueConstraint(fields=('subject_content_type', 'subject_object_id'), name='unique_registration_accounts_per_subject'),
        ),
    ]
