# Generated by Django 6.0.1 on 2026-07-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financials',
            name='authorized_capital',
        ),
        migrations.RemoveField(
            model_name='financials',
            name='paid_up_capital',
        ),
        migrations.AddField(
            model_name='financials',
            name='asset_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Asset Ratio'),
        ),
    ]
