# Generated by Django 6.0.1 on 2026-07-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_financials_authorized_capital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financials',
            name='net_profit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Net Profit'),
        ),
        migrations.AlterField(
            model_name='financials',
            name='net_worth',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Net Worth'),
        ),
        migrations.AlterField(
            model_name='financials',
            name='total_revenue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Total Revenue'),
        ),
    ]
