# Generated by Django 6.0.1 on 2026-07-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_financials_net_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankeraccounts',
            name='account_currency',
        ),
        migrations.AlterField(
            model_name='bankeraccounts',
            name='account_number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='bankeraccounts',
            name='bank_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
