# Generated by Django 6.0.1 on 2026-08-04 08:36

import apps.common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_bankeraccounts_account_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financials',
            name='financials_file',
        ),
        migrations.CreateModel(
            name='FinancialFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.common.models.FinancialFiles.financials_file_path, verbose_name='Financials File')),
                ('file_title', models.TextField(blank=True, null=True, verbose_name='File Title')),
                ('financial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_files', to='common.financials')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
