# Generated by Django 6.0.1 on 2026-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_financials_financials_file_financialfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankeraccounts',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
