# Generated by Django 6.0.1 on 2026-08-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_bankeraccounts_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankeraccounts',
            name='account_type',
            field=models.CharField(blank=True, choices=[('current', 'Current'), ('savings', 'Savings'), ('loan', 'Loan'), ('fixed_deposit', 'Fixed Deposit')], max_length=20, null=True),
        ),
    ]
