# Generated by Django 6.0.1 on 2026-08-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_bankeraccounts_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankeraccounts',
            name='account_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
