# Generated by Django 6.0.1 on 2026-08-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_bankeraccounts_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankeraccounts',
            name='narration',
            field=models.CharField(blank=True, choices=[('A', 'Very Good Credit Worthiness (Lowest Risk)'), ('B', 'Good Credit Worthiness (Low Risk)'), ('C', 'Satisfactory Credit Worthiness (Moderate Risk)'), ('D', 'No Credit Worthy'), ('E', 'Rating Suspended'), ('none', 'None')], default='none', max_length=10, null=True),
        ),
    ]
