# Generated by Django 6.0.1 on 2026-08-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_bankeraccounts_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationaccounts',
            name='is_tax_clearance_expiration_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrationaccounts',
            name='tax_clearance_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
