# Generated by Django 6.0.1 on 2026-08-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_registrationaccounts_is_tax_clearance_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankeraccounts',
            name='account_type',
            field=models.CharField(blank=True, choices=[('current', 'Current'), ('savings', 'Savings'), ('loan', 'Loan'), ('fixed_deposit', 'Fixed Deposit'), ('none', 'None')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bankeraccounts',
            name='date_of_acquirement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
