# Generated by Django 6.0.1 on 2026-07-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_first_n_405c86_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name', 'email', 'company_name'], name='users_user_first_n_65b32d_idx'),
        ),
    ]
