# Generated by Django 6.0.1 on 2026-07-25 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0002_remove_user_users_user_first_n_405c86_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_first_n_65b32d_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='client_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_client', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='user',
            name='client_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name', 'email'], name='users_user_first_n_405c86_idx'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
