# Generated by Django 6.0.1 on 2026-07-02 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject_object_id', models.PositiveIntegerField()),
                ('debtor_object_id', models.PositiveIntegerField()),
                ('creditor_name', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZiG', 'Zimbabwe Gold'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('ZAR', 'South African Rand')], default='USD', max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('claim_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('settled', 'Settled')], default='open', max_length=10)),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'db_table': 'claims',
            },
        ),
        migrations.CreateModel(
            name='CourtJudgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject_object_id', models.PositiveIntegerField()),
                ('court_name', models.CharField(max_length=255)),
                ('case_number', models.CharField(max_length=100)),
                ('judgement_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZiG', 'Zimbabwe Gold'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('ZAR', 'South African Rand')], default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'verbose_name': 'Court Judgement',
                'verbose_name_plural': "Court Judgement's",
                'db_table': 'court_judgement',
            },
        ),
        migrations.CreateModel(
            name='InsolvencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject_object_id', models.PositiveIntegerField()),
                ('insolvency_type', models.CharField(choices=[('insolvency', 'Insolvency'), ('bankruptcy', 'Bankruptcy'), ('judicial_management', 'Judicial Management')], max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('court_reference', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Insolvency Record',
                'verbose_name_plural': 'Insolvency Records',
                'db_table': 'insolvency_record',
            },
        ),
        migrations.CreateModel(
            name='PublicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject_object_id', models.PositiveIntegerField()),
                ('record_date', models.DateField(blank=True, null=True, verbose_name='Record Date')),
                ('summary', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Public Information',
                'verbose_name_plural': 'Public Information',
                'db_table': 'public_information',
            },
        ),
        migrations.CreateModel(
            name='Absconders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject_object_id', models.PositiveIntegerField()),
                ('debtor_object_id', models.PositiveIntegerField()),
                ('creditor_name', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZiG', 'Zimbabwe Gold'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('ZAR', 'South African Rand')], default='USD', max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('settled', 'Settled'), ('disputed', 'Disputed'), ('written_off', 'Written Off')], default='open', max_length=20)),
                ('debtor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_debtor', to='contenttypes.contenttype')),
                ('subject_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subject', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Absconder Record',
                'verbose_name_plural': 'Absconder Records',
                'db_table': 'absconder',
            },
        ),
    ]
