# Generated by Django 6.0.1 on 2026-07-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_records', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insolvencyrecord',
            name='insolvency_type',
            field=models.CharField(choices=[('insolvent', 'Insolvent'), ('judicial_management', 'Judicial Management')], max_length=30),
        ),
    ]
