# Generated by Django 6.0.1 on 2026-08-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_records', '0003_alter_insolvencyrecord_insolvency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='overdue_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
