# Generated by Django 6.0.1 on 2026-08-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_records', '0004_claims_overdue_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='absconders',
            name='overdue_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
