# Generated by Django 6.0.1 on 2026-08-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_records', '0005_absconders_overdue_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='absconders',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='claims',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='courtjudgement',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('settled', 'Settled'), ('disputed', 'Disputed'), ('written_off', 'Written Off')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='absconders',
            name='creditor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='claims',
            name='creditor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courtjudgement',
            name='case_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courtjudgement',
            name='court_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
