# Generated by Django 6.0.1 on 2026-08-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_records', '0006_absconders_account_number_claims_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtjudgement',
            name='plaintf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courtjudgement',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZiG', 'Zimbabwe Gold'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('ZAR', 'South African Rand')], default='USD', max_length=4),
        ),
    ]
