# Generated by Django 6.0.1 on 2026-08-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_records', '0007_courtjudgement_plaintf_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('settled', 'Settled'), ('disputed', 'Disputed'), ('written_off', 'Written Off')], default='open', max_length=25),
        ),
    ]
