# Generated by Django 6.0.1 on 2026-07-02 08:44

import apps.reports.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subject_object_id', models.PositiveIntegerField()),
                ('client_object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=20)),
                ('overall_risk_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('enquiry_reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('snapshot', models.JSONField(default=dict, verbose_name='Holds how the data was for the subject at the date of finalization')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to=apps.reports.models.report_pdf_path, verbose_name='Report PDF')),
                ('client_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_clients', to='contenttypes.contenttype')),
                ('subject_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_subject', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Enquiry Report',
                'verbose_name_plural': 'Enquiry Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
