# Generated by Django 6.0.1 on 2026-07-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_username_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='snapshot',
            field=models.JSONField(default=dict, verbose_name='Data ScreenShot'),
        ),
    ]
