# Generated by Django 6.0.1 on 2026-07-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_is_stale_report_suspension_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='is_stale',
        ),
    ]
