# Generated by Django 6.0.1 on 2026-08-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_report_is_stale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('suspended', 'Suspended'), ('finalized', 'Finalized')], default='in_progress', max_length=20),
        ),
    ]
