# Generated by Django 6.0.1 on 2026-08-28 20:40

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_contact_person_alter_report_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': [models.OrderBy(django.db.models.functions.comparison.Coalesce('report_date', 'created_at'), descending=True)], 'verbose_name': 'Enquiry Report', 'verbose_name_plural': 'Enquiry Reports'},
        ),
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
