# Generated by Django 6.0.1 on 2026-07-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Employer')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position')),
                ('employment_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Employment Status')),
                ('years_employed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Years Employed')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monthly Income')),
                ('previous_employer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Previous Employer')),
            ],
            options={
                'verbose_name': 'Employment Information',
                'verbose_name_plural': 'Employment Informations',
                'ordering': ['employer', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Individuals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Full name')),
                ('national_id', models.CharField(max_length=100, unique=True, verbose_name='National ID / Passport')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=50, verbose_name='Marital status')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('residential_address', models.TextField(verbose_name='Residential address')),
                ('mobile_number', models.CharField(max_length=50, verbose_name='Mobile number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('refer_type', models.CharField(choices=[('biu', 'BIU'), ('fp3', 'FP3'), ('rentsafe', 'Rentsafe')], default='biu', help_text='Where was individual data retrieved from, default is BIU.', max_length=10)),
            ],
            options={
                'verbose_name': 'Individual',
                'verbose_name_plural': 'Individuals',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('relationship', models.CharField(max_length=100, verbose_name='Relationship')),
                ('contact_number', models.CharField(max_length=50, verbose_name='Contact Number')),
            ],
            options={
                'verbose_name': 'Next of Kin / Reference',
                'verbose_name_plural': 'Next of Kin / References',
                'ordering': ['name'],
            },
        ),
    ]
