# Generated by Django 6.0.1 on 2026-07-02 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individuals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinformation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individuals',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employmentinformation',
            name='individual',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_information', to='individuals.individuals'),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='individual',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='individuals.individuals'),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='individuals',
            constraint=models.UniqueConstraint(fields=('national_id',), name='unique_national_id'),
        ),
    ]
