# Generated by Django 6.0.1 on 2026-08-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuals',
            name='residential_address',
            field=models.TextField(blank=True, null=True, verbose_name='Residential address'),
        ),
    ]
