# Generated by Django 6.0.1 on 2026-08-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0003_alter_individuals_residential_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuals',
            name='address_prev',
            field=models.TextField(blank=True, help_text='Director Prev Address', null=True),
        ),
        migrations.AddField(
            model_name='individuals',
            name='insolvencies_judgements',
            field=models.TextField(blank=True, null=True, verbose_name='Insolvencies, Judgements, Defaults'),
        ),
        migrations.AddField(
            model_name='individuals',
            name='is_pep',
            field=models.BooleanField(default=False),
        ),
    ]
