# Generated by Django 6.0.1 on 2026-08-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0004_individuals_address_prev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuals',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full name'),
        ),
    ]
