# Generated by Django 6.0.1 on 2026-08-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0005_alter_individuals_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuals',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality'),
        ),
    ]
