# Generated by Django 6.0.1 on 2026-08-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0006_alter_individuals_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuals',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile number'),
        ),
    ]
