# Generated by Django 6.0.1 on 2026-08-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0007_alter_individuals_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuals',
            name='national_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='National ID / Passport'),
        ),
    ]
